CREATE TABLE WORKER (	
	NUM_ID_WORKER NUMBER GENERATED ALWAYS AS IDENTITY,
	NUM_ID_STATUS NUMBER NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DAILY_INCOME DECIMAL(10,2),
	DAT_CRIACAO DATE NOT NULL,
	PRIMARY KEY(NUM_ID_WORKER)
);

CREATE TABLE STATUS (
	NUM_ID_STATUS NUMBER GENERATED ALWAYS AS IDENTITY,
	NOM_STATUS VARCHAR2(15) NOT NULL,
	PRIMARY KEY(NUM_ID_STATUS)
);

ALTER TABLE WORKER ADD CONSTRAINT FK_NUM_ID_STATUS FOREIGN KEY (NUM_ID_STATUS) REFERENCES STATUS(NUM_ID_STATUS);
