INSERT INTO STATUS (NOM_STATUS) VALUES ('Pendente');
INSERT INTO STATUS (NOM_STATUS) VALUES ('Ativo');
INSERT INTO STATUS (NOM_STATUS) VALUES ('Restrito');
INSERT INTO STATUS (NOM_STATUS) VALUES ('Inativo');